### ISSUE TITLE
Expose metrics and tracing

### ISSUE THREAD

**Issue by donovanmuller** [AbsaOSS/ohmyglb#47]
Implement relevant metrics that provide insight into:

* Edge DNS integrations
* Split brain scenarios / heartbeat
* Reconciliation
* Load balancing strategies
* etc.

Metrics should be expressed as Prometheus [text exposition format](https://github.com/prometheus/docs/blob/master/content/docs/instrumenting/exposition_formats.md).

Consider the following CoreDNS plugins as reference:

* https://coredns.io/plugins/metrics/
* https://coredns.io/plugins/trace/

**Comment by somaritane** [comment]
https://github.com/AbsaOSS/ohmyglb/pull/97 addresses generation of initial scope of prometheus metrics for the project.
Metrics are exposed at prometheus endpoints, and can scraped with 3rd party tools, as well as [Prometheus Operator](https://github.com/coreos/prometheus-operator).
Since the scope of this issue is really wide, I suggest to chop it to smaller pieces (additional metrics, tracing support) and resolve the original, considering #97 is merged.
