### ISSUE TITLE
Upgrade underlying operator-sdk version from v0.12.0 to latest upstream

### ISSUE THREAD

**Issue by ytsarev** [AbsaOSS/ohmyglb#71]
Originally `ohmyglb` operator was generated with `operator-sdk` version `v0.12.0`

There is no urgent need but eventually we might want to upgrade to latest `v0.16.0` ( at the time of writing)

Upgrade path doc upstream: https://github.com/operator-framework/operator-sdk/blob/master/doc/migration/version-upgrade-guide.md

I would suggest we make it after implementation of strong e2e test suite to avoid wasting time on manual e2e regression testing

**Comment by kuritka** [comment]
In package dependency tree you can find github.com/openshift/api v3.9.1 but github.com/openshift/api is no longer tagged. After cleaning package cache `go clean -modcache && make build` you obtain something like this `github.com/openshift/api@v3.9.1-0.20190424152011-77b8897ec79a+incompatible: invalid pseudo-version: preceding tag (v3.9.0) not found`

You can obtain error by downloading newest operator framework and running `go mod download` to populate go cache or upgrading GSLB to newer version

**Comment by ytsarev** [comment]
@somaritane @kuritka maybe we should deprecate `/vendor` completely as part of the upgrade

**Comment by kuritka** [comment]
@somaritane @ytsarev  - Hi deprecating /vendor is step right way. 

 module versions are kept within `go.mod` and  modules are physically in `src/pkg/mod/...`.  Regarding pipeline  `\vendor` folder is skipping anyway  because `go build .` in Go 1.13 reads modules from `src/pkg/mod/...`  (viz demo below). Also package verification (`go mod verify`) is impossible on vendoring folders (plan is go 1.15).  /vendor is fine when your build server cannot download from internet etc.. 

viz demo:
```
## <= go 1.13
```bash
go mod edit -go 1.13

go run -mod=vendor ./main.go
# HELLO FROM VENDOR

go run ./main.go
# Hello from /src/pkg/mod/github.com/kuritka/gext

go mod edit -go 1.14

go run -mod=vendor ./main.go
# HELLO FROM VENDOR

```

Also consider upgrading to Go to 1.14

**Comment by somaritane** [comment]
@ytsarev @kuritka As I was trying upgrade to v0.16.0, the idea to opt out from vendoring came to my mind too :)
The work is in https://github.com/AbsaOSS/ohmyglb/tree/upgrade-operator-sdk-v0.16.0 branch, PR is coming soon...
